name: ps5-payload-libs

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo apt update
        sudo apt install cmake pkg-config meson clang-18 lld-18
        sudo apt install build-essential autoconf libtool yasm nasm
        sudo apt install smpq gperf pkgconf libarchive-tools autopoint po4a git curl doxygen
        sudo apt install makepkg pacman-package-manager python3-mako
        sudo apt install tcl

    - name: Build Libs
      run: bash ci-libs.sh

    - name: Package Libs
      run: tar -czf ps5-payload-libs.tar.gz -C / opt/ps5-payload-sdk

    - name: Upload Libs
      uses: actions/upload-artifact@v4
      with:
        name: ps5-payload-libs
        path: ./ps5-payload-libs.tar.gz
        if-no-files-found: error
